import distribution_functions_associated_additive_positive_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace distribution_functions_associated_additive_positive_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end distribution_functions_associated_additive_positive_theorem_canonical_lane_mathlib
end HautevilleHouse
